teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: flash_robot/cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 200.0
      -
        axis: 0
        target: angular.z
        scale: 20.0
  look:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: flash_robot/cmd_vel
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 4
        target: angular.z
        scale: 1.0
      -
        axis: 3
        target: angular.y
        scale: 1.0
  behave:
    type: topic
    message_type: std_msgs/Int16
    topic_name: flash_robot/behave
    buttons: [0]
    message_value:
      -
        target: data
        value: 1    
    buttons: [1]
    message_value:
      -
        target: data
        value: 2    
    buttons: [2]
    message_value:
      -
        target: data
        value: 3    
    buttons: [3]
    message_value:
      -
        target: data
        value: 4    
        