teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: flash_robot/cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 1.0
  look:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: flash_robot/head/cmd_vel
    deadman_buttons: [5]
    axis_mappings:
      -
        axis: 4
        target: angular.z
        scale: 0.1
      -
        axis: 3
        target: angular.y
        scale: 0.1
  behaveA:
    type: topic
    message_type: std_msgs/Int16
    topic_name: flash_robot/behave
    buttons: [0]
    message_value:
      -
        target: data
        value: 1    
  behaveB:
    type: topic
    message_type: std_msgs/Int16
    topic_name: flash_robot/behave
    buttons: [1]
    message_value:
      -
        target: data
        value: 2    
  behaveX:
    type: topic
    message_type: std_msgs/Int16
    topic_name: flash_robot/behave
    buttons: [2]
    message_value:
      -
        target: data
        value: 3    
  behaveY:
    type: topic
    message_type: std_msgs/Int16
    topic_name: flash_robot/behave
    buttons: [3]
    message_value:
      -
        target: data
        value: 4    
        
