<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="flash">

  <xacro:include filename="$(find flash_description)/urdf/sensors/hokuyo_urg_04lx_ug01_laser.urdf.xacro"/>
  
  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Materials -->
  <material name="gray">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>
  <material name="dark_gray">
    <color rgba="0.2 0.2 0.2 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  
  <!-- Base -->
  <link name="base_footprint"/>

  <xacro:property name="base_width" value="0.61"/>
  <xacro:property name="base_depth" value="0.361"/>
  <xacro:property name="base_height" value="0.4"/>
  <xacro:property name="distance_from_ground" value="0.04"/>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_depth} ${base_width} ${base_height}"/>
        <origin rpy="0 0 0" xyz="0 0 ${base_height/2 + 0.04}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${base_height/2 + distance_from_ground}"/>
  </joint>

  <!-- Wheels -->
  <xacro:property name="wheel_diameter" value="0.316"/>
  <xacro:property name="wheel_thickness" value="0.05"/>
  <xacro:property name="wheel_separation" value="0.01"/>
  <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_thickness}" radius="${wheel_diameter/2}"/>
        </geometry>
        <material name="gray"/>
      </visual>
    </link>

    <joint name="base_to_${prefix}_wheel" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin rpy="-1.57075 0 0" xyz="0 ${reflect*(base_width/2 + wheel_thickness/2 + wheel_separation)} ${-(base_height/2 + distance_from_ground) + wheel_diameter/2}"/>
    </joint>
  </xacro:macro>
  
  <xacro:leg prefix="right" reflect="-1" />
  <xacro:leg prefix="left" reflect="1" />

  <!-- Laser -->
  <xacro:property name="base_laser_x" value="${base_depth/2 - 0.025}"/>
  <xacro:property name="base_laser_y" value="0"/>
  <xacro:property name="base_laser_z" value="${base_height/2 + 0.065}"/>
  <!-- Practical FOV = 140 -->
  <xacro:hokuyo_urg_04lx_ug01_laser name="base_laser" parent="base" ros_topic="scan" update_rate="10" min_angle="${-70 * deg_to_rad}" max_angle="${70 * deg_to_rad}" >
    <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
  </xacro:hokuyo_urg_04lx_ug01_laser>
  
</robot>
