image: /home/jose-xenial/Software/ros/kinetic/socoro_ws/src/flash_robot/flash_maps/config/lab_map.pgm
resolution: 0.050000
origin: [-100.000000, -100.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

