TrajectoryPlannerROS:
  max_vel_x: 200.0
  min_vel_x: 100.0
  max_vel_theta: 20.0
  min_in_place_vel_theta: 10.0

  acc_lim_theta: 10.0
  acc_lim_x: 50.0
  acc_lim_y: 50.0 # This is actually N/A

  holonomic_robot: false
